// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParkingBuildingManagement.Api.Data;

#nullable disable

namespace ParkingBuildingManagement.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710111927_AddUserGoogleAuthLink")]
    partial class AddUserGoogleAuthLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("FeedbackID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FeedbackType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("SessionID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("New");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.HasKey("FeedbackId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IncidentID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncidentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PenaltyFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("ReportedById")
                        .HasColumnType("integer")
                        .HasColumnName("ReportedByID");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("SessionID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Open");

                    b.HasKey("IncidentId");

                    b.HasIndex("ReportedById");

                    b.HasIndex("SessionId");

                    b.ToTable("Incidents", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.ParkingFacility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("FacilityID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FacilityId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("FacilityId");

                    b.ToTable("ParkingFacility", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.ParkingSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SessionID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionId"));

                    b.Property<string>("EntryGate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("EntryStaffId")
                        .HasColumnType("integer")
                        .HasColumnName("EntryStaffID");

                    b.Property<DateTime>("EntryTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("EstimatedFee")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ExitGate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ExitStaffId")
                        .HasColumnType("integer")
                        .HasColumnName("ExitStaffID");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("ReservationID");

                    b.Property<string>("SlotId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("SlotID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("TotalFee")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("VehicleTypeID");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("ZoneID");

                    b.HasKey("SessionId");

                    b.HasIndex("EntryStaffId");

                    b.HasIndex("ExitStaffId");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("IX_Session_LicensePlate")
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("ReservationId");

                    b.HasIndex("SlotId")
                        .HasDatabaseName("IX_Session_Slot");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Session_Status");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleTypeId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ParkingSessions", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.ParkingSlot", b =>
                {
                    b.Property<string>("SlotId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("SlotID");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Available");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("ZoneID");

                    b.HasKey("SlotId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ParkingSlots", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.ParkingZone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ZoneID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ZoneId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("VehicleTypeID");

                    b.Property<string>("ZoneCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ZoneId");

                    b.HasIndex("VehicleTypeId");

                    b.HasIndex("ZoneCode")
                        .IsUnique();

                    b.ToTable("ParkingZones", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PaymentID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("PaymentTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("SessionID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Completed");

                    b.HasKey("PaymentId");

                    b.HasIndex("SessionId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.PricingPolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PolicyID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PolicyId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("DailyMaxFee")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("LostTicketFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("OvertimeFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("VehicleTypeID");

                    b.HasKey("PolicyId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("PricingPolicies", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.ReportSnapshot", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ReportID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("OccupancyRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("PeakHour")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalEntries")
                        .HasColumnType("integer");

                    b.Property<int>("TotalExits")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(14,2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("VehicleTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("VehicleTypeID");

                    b.HasKey("ReportId");

                    b.HasIndex("VehicleTypeId");

                    b.HasIndex("ReportDate", "VehicleTypeId")
                        .IsUnique();

                    b.ToTable("ReportSnapshots", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ReservationID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("PreferVipSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ReservedFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReservedTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SlotId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("SlotID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("VehicleTypeID");

                    b.Property<decimal?>("VipSurcharge")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("ZoneID");

                    b.HasKey("ReservationId");

                    b.HasIndex("LicensePlate")
                        .HasDatabaseName("IX_Reservation_LicensePlate");

                    b.HasIndex("SlotId");

                    b.HasIndex("VehicleTypeId");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_Reservation_User_Status");

                    b.HasIndex("ZoneId", "ReservedFrom", "ReservedTo")
                        .HasDatabaseName("IX_Reservation_Zone_TimeRange");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RoleID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Staff"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Driver"
                        });
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.SystemConfig", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ConfigKey");

                    b.ToTable("SystemConfigs", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("HasLocalPassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("RoleID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<decimal>("WalletBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasFilter("\"GoogleSubject\" IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.VehicleType", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("VehicleTypeID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehicleTypeId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("VehicleTypeId");

                    b.HasIndex("TypeCode")
                        .IsUnique();

                    b.ToTable("VehicleTypes", (string)null);

                    b.HasData(
                        new
                        {
                            VehicleTypeId = 1,
                            Status = "Active",
                            TypeCode = "MOTORBIKE",
                            TypeName = "Motorbike"
                        },
                        new
                        {
                            VehicleTypeId = 2,
                            Status = "Active",
                            TypeCode = "CAR",
                            TypeName = "Car"
                        },
                        new
                        {
                            VehicleTypeId = 3,
                            Status = "Active",
                            TypeCode = "EV",
                            TypeName = "Electric Vehicle"
                        },
                        new
                        {
                            VehicleTypeId = 4,
                            Status = "Active",
                            TypeCode = "EV_MOTORBIKE",
                            TypeName = "Electric Motorbike"
                        },
                        new
                        {
                            VehicleTypeId = 5,
                            Status = "Active",
                            TypeCode = "EV_CAR",
                            TypeName = "Electric Car"
                        });
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.WalletTopUp", b =>
                {
                    b.Property<int>("TopUpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TopUpID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TopUpId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("PayOsOrderCode")
                        .HasColumnType("bigint");

                    b.Property<string>("PaymentLinkId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("QrCode")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.HasKey("TopUpId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_WalletTopUp_CreatedAt");

                    b.HasIndex("PayOsOrderCode")
                        .IsUnique();

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_WalletTopUp_User_Status");

                    b.ToTable("WalletTopUps", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.Feedback", b =>
                {
                    b.HasOne("ParkingBuildingManagement.Api.Models.ParkingSession", "Session")
                        .WithMany("Feedbacks")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingBuildingManagement.Api.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.Incident", b =>
                {
                    b.HasOne("ParkingBuildingManagement.Api.Models.User", "ReportedBy")
                        .WithMany("ReportedIncidents")
                        .HasForeignKey("ReportedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingBuildingManagement.Api.Models.ParkingSession", "Session")
                        .WithMany("Incidents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReportedBy");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.ParkingSession", b =>
                {
                    b.HasOne("ParkingBuildingManagement.Api.Models.User", "EntryStaff")
                        .WithMany("EntryStaffSessions")
                        .HasForeignKey("EntryStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingBuildingManagement.Api.Models.User", "ExitStaff")
                        .WithMany("ExitStaffSessions")
                        .HasForeignKey("ExitStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingBuildingManagement.Api.Models.Reservation", "Reservation")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingBuildingManagement.Api.Models.ParkingSlot", "Slot")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingBuildingManagement.Api.Models.User", "User")
                        .WithMany("DriverSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingBuildingManagement.Api.Models.VehicleType", "VehicleType")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingBuildingManagement.Api.Models.ParkingZone", "Zone")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntryStaff");

                    b.Navigation("ExitStaff");

                    b.Navigation("Reservation");

                    b.Navigation("Slot");

                    b.Navigation("User");

                    b.Navigation("VehicleType");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.ParkingSlot", b =>
                {
                    b.HasOne("ParkingBuildingManagement.Api.Models.ParkingZone", "Zone")
                        .WithMany("ParkingSlots")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.ParkingZone", b =>
                {
                    b.HasOne("ParkingBuildingManagement.Api.Models.VehicleType", "VehicleType")
                        .WithMany("ParkingZones")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.Payment", b =>
                {
                    b.HasOne("ParkingBuildingManagement.Api.Models.ParkingSession", "Session")
                        .WithMany("Payments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.PricingPolicy", b =>
                {
                    b.HasOne("ParkingBuildingManagement.Api.Models.VehicleType", "VehicleType")
                        .WithMany("PricingPolicies")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.ReportSnapshot", b =>
                {
                    b.HasOne("ParkingBuildingManagement.Api.Models.VehicleType", "VehicleType")
                        .WithMany("ReportSnapshots")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.Reservation", b =>
                {
                    b.HasOne("ParkingBuildingManagement.Api.Models.ParkingSlot", "Slot")
                        .WithMany("Reservations")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingBuildingManagement.Api.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingBuildingManagement.Api.Models.VehicleType", "VehicleType")
                        .WithMany("Reservations")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingBuildingManagement.Api.Models.ParkingZone", "Zone")
                        .WithMany("Reservations")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Slot");

                    b.Navigation("User");

                    b.Navigation("VehicleType");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.User", b =>
                {
                    b.HasOne("ParkingBuildingManagement.Api.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.WalletTopUp", b =>
                {
                    b.HasOne("ParkingBuildingManagement.Api.Models.User", "User")
                        .WithMany("WalletTopUps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.ParkingSession", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Incidents");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.ParkingSlot", b =>
                {
                    b.Navigation("ParkingSessions");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.ParkingZone", b =>
                {
                    b.Navigation("ParkingSessions");

                    b.Navigation("ParkingSlots");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.Reservation", b =>
                {
                    b.Navigation("ParkingSessions");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.User", b =>
                {
                    b.Navigation("DriverSessions");

                    b.Navigation("EntryStaffSessions");

                    b.Navigation("ExitStaffSessions");

                    b.Navigation("Feedbacks");

                    b.Navigation("ReportedIncidents");

                    b.Navigation("Reservations");

                    b.Navigation("WalletTopUps");
                });

            modelBuilder.Entity("ParkingBuildingManagement.Api.Models.VehicleType", b =>
                {
                    b.Navigation("ParkingSessions");

                    b.Navigation("ParkingZones");

                    b.Navigation("PricingPolicies");

                    b.Navigation("ReportSnapshots");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
